version: "3.8"

services:
  db:
    image: postgres:16-alpine
    user: postgres
    container_name: db
    environment:
      PG_USER: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: aima
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_NAME=aima
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_PORT=5432
      - APP_SALT=salt
      - APP_SECRET=accelerator
    build:
      context: .
      target: production
    ports:
      - 3000:3000

volumes:
  db_data:
    driver: local
